name: microG Build

on:
  workflow_dispatch:

env:
  TOKEN: ${{ secrets.TOKEN }}
  RELEASE: v1.8

jobs:
  build:
    if: github.repository_owner == 'BiTGApps'
    runs-on: ubuntu-latest

    steps:
       - name: Initial Setup
         uses: actions/checkout@v3

       - name: Create microG
         run: |
           rm -rf microG
           mkdir microG
           install -d out

       - name: Clone Build Sources
         run: |
           git clone https://github.com/BiTGApps/microG-Installer microG

       - name: Create Sources
         run: |
           mkdir microG/sources

       - name: Clone Package Sources
         run: |
           git clone https://github.com/BiTGApps/microG-sources microG/sources/microG-sources

       - name: Apply Systemless Patch
         env:
           GITHUB: https://raw.githubusercontent.com/BiTGApps
         run: |
           cd microG
           curl -sLo microg.patch $GITHUB/microG-Patches/master/patches/microg.patch
           git apply microg.patch
           cd ..

       - name: Build microG Package
         run: |
           cd microG
           . scripts/envsetup.sh && rm -rf scripts
           zip -qr9 MicroG-$RELEASE.zip * && cd ..
           cp -f microG/MicroG-$RELEASE.zip out

       - name: Sign microG Package
         run: |
           wget https://github.com/BiTGApps/BiTGApps/raw/master/tools/zipsigner/zipsigner.jar
           sudo java -jar zipsigner.jar out/MicroG-$RELEASE.zip out/MicroG-$RELEASE-Signed.zip
           rm -rf out/MicroG-$RELEASE.zip && mv -f out/MicroG-$RELEASE-Signed.zip out/MicroG-$RELEASE.zip

       - name: Github Release CLI
         run: |
           npm install -g github-release-cli

       - name: Release Signed Package
         env:
           PACKAGE: false
         run: |
           github-release upload \
           --owner "BiTGApps" \
           --repo "microG-Patches" \
           --token "$TOKEN" \
           --tag "${RELEASE}" \
           --release-name "MicroG ${RELEASE}" \
           "out/MicroG-$RELEASE.zip"

       - name: Upload Build Artifact
         if: ${{ env.PACKAGE == 'true' }}
         uses: actions/upload-artifact@v3
         with:
           name: microG-Build
           path: out/MicroG-$RELEASE.zip
